#!/usr/bin/env python
# Daniel Oskarsson <daniel.oskarsson@gmail.com>

import json, os
from collections import OrderedDict
from sys import argv, stdin

def parse(data):
	if (type(data) is OrderedDict):
		for key in data:
			data[key] = parse(data[key])
	elif (type(data) is list):
		items = list()
		for value in data:
			item = parse(value)
			if item not in items:
				items.append(item)
		data = items
	elif (type(data) is unicode):
		data = "string"
	elif (type(data) is float):
		data = "number"
	elif (type(data) is int):
		#data = "[0,)" if data >= 0 else "(,0)"
		data = "integer"
	elif (type(data) is bool):
		data = "boolean"
	else:
		pass
	return data

if not stdin.isatty():
	data = stdin.read()
else:
	data = open(argv[1],'r').read() if os.path.isfile(argv[1]) else argv[1]

print json.dumps(parse(json.loads(data, object_pairs_hook=OrderedDict)), indent = 4)
